### ISSUE TITLE
Add our importer gem to dlp-curate

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#11]
- [x] I can run a command line import for DCE known, good content 
- [x] Creates the expected number of works
- [x] Has at least the minimum required metadata

**Comment by bess** [comment]
Here are some title-only objects imported via command line from a customized mapper. Their data model is so customized that I could only easily find `title` as a standard field name we'd expect. I think we should start working with Emory data right away because otherwise we'll duplicate a lot of effort making a metadata mapping for our own fields and then have to do the same thing for their fields. 

Ditto with file attachments. Their expectations around file attachments are very different and I think we should just try to start doing what they're doing instead of trying to re-implement the out of the box hyrax file attachments. 

![curate_basic_command_line_import.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/33de5f12-7d36-4bd0-bede-e0fd3ea8064b)
